title: M Hamza Khalid's Portfolio

name: M Hamza Khalid
headline: Aerospace Engineer
description: >-
  Final-year Aerospace Engineering student at IST specializing in aerodynamics, CFD, and rotorcraft concepts. Passionate about innovation and future transportation systems.

profile_image: ./assets/images/profile-image/Hamza.jpg
resume-url: ./assets/images/profile-image/CV1%20(2).pdf

external-links:
  linkedin: https://www.linkedin.com/in/mhamzakhali­d100

skills:
  - category: 3D Modeling & CAD
    tools:
    - CATIA
    - SolidWorks
    - OpenVSP
  - category: Simulation
    tools:
    - ANSYS
    - QBlade
    - MATLAB
  - category: Programming
    tools:
    - Python
    - Simulink
    - MATLAB
  - category: Engineering Domains
    tools:
    - CFD
    - Propulsion
    - Structures
    - GNAV
  - category: Soft Skills
    tools:
    - Presentation
    - Team Collaboration

formspree-key: https://formspree.io/f/movdkvor

colors:
  text: "#f5f5f5"
  border: "#444"
  link: "#00ffff"
  highlight: "#00c3ff"
  background: "#000010"
  light_background: "#1a1a2e"

collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

include:
  - _projects
